CREATE TABLE "properties" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"contact_id" uuid NOT NULL,
	"address" text NOT NULL,
	"year_built" integer,
	"year_purchased" integer,
	"bedrooms" integer,
	"full_bathrooms" integer,
	"half_bathrooms" integer,
	"garage_type" varchar(50),
	"garage_capacity" integer,
	"electric_provider" varchar(100),
	"electric_avg_bill" varchar(50),
	"water_provider" varchar(100),
	"water_avg_bill" varchar(50),
	"trash_provider" varchar(100),
	"trash_avg_bill" varchar(50),
	"internet_provider" varchar(100),
	"internet_avg_bill" varchar(50),
	"internet_speed" varchar(50),
	"heating_type" varchar(100),
	"heating_age" varchar(50),
	"cooling_type" varchar(100),
	"cooling_age" varchar(50),
	"water_heater_type" varchar(50),
	"roof_type" varchar(50),
	"roof_age" varchar(50),
	"septic_sewer" varchar(20),
	"septic_size" varchar(50),
	"septic_last_cleaned" varchar(50),
	"water_source" varchar(100),
	"security_system" varchar(100),
	"cameras_convey" varchar(20),
	"insurance_company" varchar(100),
	"insurance_annual_premium" varchar(50),
	"annual_taxes" varchar(50),
	"termite_company" varchar(100),
	"termite_annual_cost" varchar(50),
	"appliances_notes" text,
	"negotiation_items" text,
	"marketing_love_notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "properties" ADD CONSTRAINT "properties_contact_id_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."contacts"("id") ON DELETE cascade ON UPDATE no action;